r"""
Concrete cell class definition.

This module was autogenerated from:

def make_class(vtk_class_name):
    pv_class_name = vtk_class_name[3:]
    return f'''class {pv_class_name}(_vtk.{vtk_class_name}, Cell):
    '''Wrap {vtk_class_name}.'''

    def __init__(self, *args, **kwargs):
        '''Initialize cell.'''
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        '''Return the object representation.'''
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        '''Return the object string representation.'''
        return self.head(display=False, html=False)'''


from vtkmodules import vtkCommonDataModel

vtk_classes = []
for item in dir(vtkCommonDataModel):
    if item.startswith('vtkCell'):
        continue
    cell_type = getattr(vtkCommonDataModel, item)
    if cell_type.__class__ is type:
        if issubclass(cell_type, vtkCommonDataModel.vtkCell):
            print(make_class(item))
            print('\n')
            vtk_classes.append(item)

print('_cell_map = {')
for vtk_class_name in vtk_classes:
    pv_class_name = vtk_class_name[3:]
    print(f'    _vtk.{vtk_class_name}: {pv_class_name},')
print('}')


"""
from pyvista import _vtk

from .cell import Cell


def wrap_cell(vtk_cell, deep=False):
    """Wrap a given vtk cell to a PyVista cell."""
    return _cell_map[type(vtk_cell)](vtk_cell, deep=deep)


class Tetra(_vtk.vtkTetra, Cell):
    """Wrap vtkTetra."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class BezierCurve(_vtk.vtkBezierCurve, Cell):
    """Wrap vtkBezierCurve."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class BezierHexahedron(_vtk.vtkBezierHexahedron, Cell):
    """Wrap vtkBezierHexahedron."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class BezierQuadrilateral(_vtk.vtkBezierQuadrilateral, Cell):
    """Wrap vtkBezierQuadrilateral."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class BezierTetra(_vtk.vtkBezierTetra, Cell):
    """Wrap vtkBezierTetra."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class BezierTriangle(_vtk.vtkBezierTriangle, Cell):
    """Wrap vtkBezierTriangle."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class BezierWedge(_vtk.vtkBezierWedge, Cell):
    """Wrap vtkBezierWedge."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class BiQuadraticQuad(_vtk.vtkBiQuadraticQuad, Cell):
    """Wrap vtkBiQuadraticQuad."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class BiQuadraticQuadraticHexahedron(_vtk.vtkBiQuadraticQuadraticHexahedron, Cell):
    """Wrap vtkBiQuadraticQuadraticHexahedron."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class BiQuadraticQuadraticWedge(_vtk.vtkBiQuadraticQuadraticWedge, Cell):
    """Wrap vtkBiQuadraticQuadraticWedge."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class BiQuadraticTriangle(_vtk.vtkBiQuadraticTriangle, Cell):
    """Wrap vtkBiQuadraticTriangle."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class ConvexPointSet(_vtk.vtkConvexPointSet, Cell):
    """Wrap vtkConvexPointSet."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class CubicLine(_vtk.vtkCubicLine, Cell):
    """Wrap vtkCubicLine."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class EmptyCell(_vtk.vtkEmptyCell, Cell):
    """Wrap vtkEmptyCell."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class GenericCell(_vtk.vtkGenericCell, Cell):
    """Wrap vtkGenericCell."""

    def __init__(self, vtk_cell=None, deep=False, cell_type=None):
        """Initialize cell."""
        if cell_type is not None:
            self.SetCellType(cell_type)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class HexagonalPrism(_vtk.vtkHexagonalPrism, Cell):
    """Wrap vtkHexagonalPrism."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Hexahedron(_vtk.vtkHexahedron, Cell):
    """Wrap vtkHexahedron."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class HigherOrderCurve(_vtk.vtkHigherOrderCurve, Cell):
    """Wrap vtkHigherOrderCurve."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class HigherOrderHexahedron(_vtk.vtkHigherOrderHexahedron, Cell):
    """Wrap vtkHigherOrderHexahedron."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class HigherOrderQuadrilateral(_vtk.vtkHigherOrderQuadrilateral, Cell):
    """Wrap vtkHigherOrderQuadrilateral."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class HigherOrderTetra(_vtk.vtkHigherOrderTetra, Cell):
    """Wrap vtkHigherOrderTetra."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class HigherOrderTriangle(_vtk.vtkHigherOrderTriangle, Cell):
    """Wrap vtkHigherOrderTriangle."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class HigherOrderWedge(_vtk.vtkHigherOrderWedge, Cell):
    """Wrap vtkHigherOrderWedge."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class LagrangeCurve(_vtk.vtkLagrangeCurve, Cell):
    """Wrap vtkLagrangeCurve."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class LagrangeHexahedron(_vtk.vtkLagrangeHexahedron, Cell):
    """Wrap vtkLagrangeHexahedron."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class LagrangeQuadrilateral(_vtk.vtkLagrangeQuadrilateral, Cell):
    """Wrap vtkLagrangeQuadrilateral."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class LagrangeTetra(_vtk.vtkLagrangeTetra, Cell):
    """Wrap vtkLagrangeTetra."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class LagrangeTriangle(_vtk.vtkLagrangeTriangle, Cell):
    """Wrap vtkLagrangeTriangle."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class LagrangeWedge(_vtk.vtkLagrangeWedge, Cell):
    """Wrap vtkLagrangeWedge."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Line(_vtk.vtkLine, Cell):
    """Wrap vtkLine."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class NonLinearCell(_vtk.vtkNonLinearCell, Cell):
    """Wrap vtkNonLinearCell."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class PentagonalPrism(_vtk.vtkPentagonalPrism, Cell):
    """Wrap vtkPentagonalPrism."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Pixel(_vtk.vtkPixel, Cell):
    """Wrap vtkPixel."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class PolyLine(_vtk.vtkPolyLine, Cell):
    """Wrap vtkPolyLine."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class PolyVertex(_vtk.vtkPolyVertex, Cell):
    """Wrap vtkPolyVertex."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Polygon(_vtk.vtkPolygon, Cell):
    """Wrap vtkPolygon."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Polyhedron(_vtk.vtkPolyhedron, Cell):
    """Wrap vtkPolyhedron."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Pyramid(_vtk.vtkPyramid, Cell):
    """Wrap vtkPyramid."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Quad(_vtk.vtkQuad, Cell):
    """Wrap vtkQuad."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class QuadraticEdge(_vtk.vtkQuadraticEdge, Cell):
    """Wrap vtkQuadraticEdge."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class QuadraticHexahedron(_vtk.vtkQuadraticHexahedron, Cell):
    """Wrap vtkQuadraticHexahedron."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class QuadraticLinearQuad(_vtk.vtkQuadraticLinearQuad, Cell):
    """Wrap vtkQuadraticLinearQuad."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class QuadraticLinearWedge(_vtk.vtkQuadraticLinearWedge, Cell):
    """Wrap vtkQuadraticLinearWedge."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class QuadraticPolygon(_vtk.vtkQuadraticPolygon, Cell):
    """Wrap vtkQuadraticPolygon."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class QuadraticPyramid(_vtk.vtkQuadraticPyramid, Cell):
    """Wrap vtkQuadraticPyramid."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class QuadraticQuad(_vtk.vtkQuadraticQuad, Cell):
    """Wrap vtkQuadraticQuad."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class QuadraticTetra(_vtk.vtkQuadraticTetra, Cell):
    """Wrap vtkQuadraticTetra."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class QuadraticTriangle(_vtk.vtkQuadraticTriangle, Cell):
    """Wrap vtkQuadraticTriangle."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class QuadraticWedge(_vtk.vtkQuadraticWedge, Cell):
    """Wrap vtkQuadraticWedge."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class TriQuadraticHexahedron(_vtk.vtkTriQuadraticHexahedron, Cell):
    """Wrap vtkTriQuadraticHexahedron."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class TriQuadraticPyramid(_vtk.vtkTriQuadraticPyramid, Cell):
    """Wrap vtkTriQuadraticPyramid."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Triangle(_vtk.vtkTriangle, Cell):
    """Wrap vtkTriangle."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class TriangleStrip(_vtk.vtkTriangleStrip, Cell):
    """Wrap vtkTriangleStrip."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Vertex(_vtk.vtkVertex, Cell):
    """Wrap vtkVertex."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Voxel(_vtk.vtkVoxel, Cell):
    """Wrap vtkVoxel."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


class Wedge(_vtk.vtkWedge, Cell):
    """Wrap vtkWedge."""

    def __init__(self, *args, **kwargs):
        """Initialize cell."""
        super().__init__(*args, **kwargs)

    def __repr__(self) -> str:
        """Return the object representation."""
        return self.head(display=False, html=False)

    def __str__(self) -> str:
        """Return the object string representation."""
        return self.head(display=False, html=False)


_cell_map = {
    _vtk.vtkBezierCurve: BezierCurve,
    _vtk.vtkBezierHexahedron: BezierHexahedron,
    _vtk.vtkBezierQuadrilateral: BezierQuadrilateral,
    _vtk.vtkBezierTetra: BezierTetra,
    _vtk.vtkBezierTriangle: BezierTriangle,
    _vtk.vtkBezierWedge: BezierWedge,
    _vtk.vtkBiQuadraticQuad: BiQuadraticQuad,
    _vtk.vtkBiQuadraticQuadraticHexahedron: BiQuadraticQuadraticHexahedron,
    _vtk.vtkBiQuadraticQuadraticWedge: BiQuadraticQuadraticWedge,
    _vtk.vtkBiQuadraticTriangle: BiQuadraticTriangle,
    _vtk.vtkConvexPointSet: ConvexPointSet,
    _vtk.vtkCubicLine: CubicLine,
    _vtk.vtkEmptyCell: EmptyCell,
    _vtk.vtkGenericCell: GenericCell,
    _vtk.vtkHexagonalPrism: HexagonalPrism,
    _vtk.vtkHexahedron: Hexahedron,
    _vtk.vtkHigherOrderCurve: HigherOrderCurve,
    _vtk.vtkHigherOrderHexahedron: HigherOrderHexahedron,
    _vtk.vtkHigherOrderQuadrilateral: HigherOrderQuadrilateral,
    _vtk.vtkHigherOrderTetra: HigherOrderTetra,
    _vtk.vtkHigherOrderTriangle: HigherOrderTriangle,
    _vtk.vtkHigherOrderWedge: HigherOrderWedge,
    _vtk.vtkLagrangeCurve: LagrangeCurve,
    _vtk.vtkLagrangeHexahedron: LagrangeHexahedron,
    _vtk.vtkLagrangeQuadrilateral: LagrangeQuadrilateral,
    _vtk.vtkLagrangeTetra: LagrangeTetra,
    _vtk.vtkLagrangeTriangle: LagrangeTriangle,
    _vtk.vtkLagrangeWedge: LagrangeWedge,
    _vtk.vtkLine: Line,
    _vtk.vtkNonLinearCell: NonLinearCell,
    _vtk.vtkPentagonalPrism: PentagonalPrism,
    _vtk.vtkPixel: Pixel,
    _vtk.vtkPolyLine: PolyLine,
    _vtk.vtkPolyVertex: PolyVertex,
    _vtk.vtkPolygon: Polygon,
    _vtk.vtkPolyhedron: Polyhedron,
    _vtk.vtkPyramid: Pyramid,
    _vtk.vtkQuad: Quad,
    _vtk.vtkQuadraticEdge: QuadraticEdge,
    _vtk.vtkQuadraticHexahedron: QuadraticHexahedron,
    _vtk.vtkQuadraticLinearQuad: QuadraticLinearQuad,
    _vtk.vtkQuadraticLinearWedge: QuadraticLinearWedge,
    _vtk.vtkQuadraticPolygon: QuadraticPolygon,
    _vtk.vtkQuadraticPyramid: QuadraticPyramid,
    _vtk.vtkQuadraticQuad: QuadraticQuad,
    _vtk.vtkQuadraticTetra: QuadraticTetra,
    _vtk.vtkQuadraticTriangle: QuadraticTriangle,
    _vtk.vtkQuadraticWedge: QuadraticWedge,
    _vtk.vtkTetra: Tetra,
    _vtk.vtkTriQuadraticHexahedron: TriQuadraticHexahedron,
    _vtk.vtkTriQuadraticPyramid: TriQuadraticPyramid,
    _vtk.vtkTriangle: Triangle,
    _vtk.vtkTriangleStrip: TriangleStrip,
    _vtk.vtkVertex: Vertex,
    _vtk.vtkVoxel: Voxel,
    _vtk.vtkWedge: Wedge,
}
