image:
  file: docker/dev-gitpod.Dockerfile

# --------------------------------------------------------
# exposing ports for liveserve
ports:
  - port: 5500
    onOpen: notify
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ritwickdey.liveserver

tasks:
  - init: |
      pip install --upgrade pip
      pip install -e . --group dev --no-cache-dir
      pre-commit install --install-hooks
