image:
  file: docker/dev-gitpod.Dockerfile

# --------------------------------------------------------
# exposing ports for liveserve
ports:
  - port: 5500
    onOpen: notify
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ritwickdey.liveserver

tasks:
  - init: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      source $HOME/.cargo/env
      uv sync --group dev
      pre-commit install --install-hooks
