"""Tests for the Open Graph descriptions generated for each documentation page.

The ``og:image`` half of PyVista's Open Graph integration is covered by
:mod:`tests.plotting.test_tinypages`; this module covers the descriptions, which are
independent of the plot directive. Both build the same ``tinypages`` project.

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
from sphinx_autoopengraph._description import _truncate

from pyvista.plotting import system_supports_plotting
from tests.plotting.test_tinypages import ENVIRONMENT_HOOKS
from tests.plotting.test_tinypages import _run_sphinx_build
from tests.plotting.test_tinypages import _sphinx_build_cmd
from tests.plotting.test_tinypages import copy_tinypages
from tests.plotting.test_tinypages import meta_tags

if TYPE_CHECKING:
    from pathlib import Path

pytest.importorskip('sphinx')

# skip all tests if unable to render
if not system_supports_plotting():
    pytestmark = pytest.mark.skip(reason='Requires system to support plotting')

# The ``sphinxext-opengraph`` default, which ``tinypages`` does not override
DESCRIPTION_LENGTH = 200


def _build(tmp_path: Path, conf_extra: str = '') -> Path:
    """Build ``tinypages`` and return its html directory."""
    with pytest.MonkeyPatch.context() as monkeypatch:
        for hook in ENVIRONMENT_HOOKS:
            monkeypatch.delenv(hook, raising=False)
        source_dir = copy_tinypages(tmp_path)
        if conf_extra:
            with (source_dir / 'conf.py').open('a', encoding='utf-8') as conf:
                conf.write(f'\n{conf_extra}\n')
        html_dir = tmp_path / 'html'
        returncode, out, err = _run_sphinx_build(
            _sphinx_build_cmd(source_dir, html_dir, tmp_path / 'doctrees'),
        )
    assert returncode == 0, f'sphinx build failed with stdout:\n{out}\nstderr:\n{err}\n'
    return html_dir


@pytest.fixture(scope='module')
def html_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Build ``tinypages`` once for every description test."""
    return _build(tmp_path_factory.mktemp('opengraph_description'))


def description(html_dir: Path, page: str) -> str:
    """Return a built page's ``og:description``."""
    tags = meta_tags(html_dir / page)
    assert 'og:description' in tags, f'{page} has no og:description'
    return tags['og:description']


def test_description_uses_the_page_introduction(html_dir: Path):
    """A prose page is described by the text under its title."""
    assert description(html_dir, 'index.html').startswith(
        'Tinypages is a tiny Sphinx project used to test PyVista'
    )


def test_description_uses_the_docstring_summary(html_dir: Path):
    """An API page is described by its docstring, not by its rendered examples.

    Sphinx wraps autodoc output in a ``desc`` node, which subclasses
    ``docutils.nodes.Admonition``. ``sphinxext-opengraph`` skips every admonition, so
    without PyVista's own parser these pages have no description at all.
    """
    text = description(html_dir, 'some_autodocs.html')

    assert text.startswith(
        'Make a sphere. Test that the pyvista-plot directive works correctly when '
        'there is something to plot.'
    )


def test_description_uses_the_gallery_example_introduction(html_dir: Path):
    """A gallery example is described by its own docstring."""
    assert description(html_dir, 'gallery/plot_gallery_thumbnail.html').startswith(
        'Draw a rising line and then a falling one, and pick the second as the thumbnail.'
    )


@pytest.mark.parametrize(
    'page',
    ['index.html', 'some_plots.html', 'some_autodocs.html', 'gallery/plot_gallery_default.html'],
)
def test_description_excludes_page_furniture(html_dir: Path, page: str):
    """Descriptions are prose only, never navigation, code or download links."""
    text = description(html_dir, page)

    assert 'Download' not in text  # sphinx-examples-as-code and Sphinx-Gallery links
    assert 'Total running time' not in text  # Sphinx-Gallery timing footer
    assert 'Gallery generated by' not in text  # Sphinx-Gallery signature
    assert '>>>' not in text  # doctest blocks
    assert 'import pyvista' not in text  # code blocks


@pytest.mark.parametrize('page', ['index.html', 'some_plots.html', 'some_autodocs.html'])
def test_description_fits_the_configured_length(html_dir: Path, page: str):
    """Descriptions honour ``ogp_description_length``."""
    assert len(description(html_dir, page)) <= DESCRIPTION_LENGTH


# The description Sphinx-Gallery's own furniture would otherwise leak into
GALLERY_DEFAULT_DESCRIPTION = (
    'Draw two lines without selecting a thumbnail, so the gallery uses the first. '
    'The first image is the gallery thumbnail by default. The second image is never '
    'used as a thumbnail.'
)


def test_gallery_description_excludes_raw_download_note(html_dir: Path):
    """Sphinx-Gallery's own "go to the end to download" banner never leaks in.

    ``tinypages`` does not configure ``sphinx-examples-as-code``'s
    ``gallery_downloads`` (see ``test_gallery_description_with_examples_as_code``
    for that), so this is Sphinx-Gallery's default download banner, not the one
    ``sphinx-examples-as-code`` inserts in its place when enabled.
    """
    page = html_dir / 'gallery' / 'plot_gallery_default.html'
    html = page.read_text(encoding='utf-8')
    # Not a vacuous check: the banner actually is on the page, just not in the description
    assert 'sphx-glr-download-link-note' in html
    assert 'download the full example code' in html

    assert description(html_dir, 'gallery/plot_gallery_default.html') == (
        GALLERY_DEFAULT_DESCRIPTION
    )


def test_gallery_description_with_examples_as_code(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """The description agrees whether or not ``sphinx-examples-as-code`` overrides the page.

    With ``gallery_downloads`` enabled, ``sphinx-examples-as-code`` removes
    Sphinx-Gallery's own download banner and replaces it with its own "Download
    Python source code | Download Jupyter notebook" links -- also not in the
    description, and via an entirely different node structure (a plain paragraph of
    ``download_reference`` nodes, not a ``sphx-glr-download-link-note`` admonition).
    """
    for hook in ENVIRONMENT_HOOKS:
        monkeypatch.delenv(hook, raising=False)
    source_dir = copy_tinypages(tmp_path)
    with (source_dir / 'conf.py').open('a', encoding='utf-8') as conf:
        conf.write("\nsphinx_examples_as_code_conf['gallery_downloads'] = True\n")

    html_dir = tmp_path / 'html'
    returncode, out, err = _run_sphinx_build(
        _sphinx_build_cmd(source_dir, html_dir, tmp_path / 'doctrees'),
    )
    assert returncode == 0, f'sphinx build failed with stdout:\n{out}\nstderr:\n{err}\n'

    page = html_dir / 'gallery' / 'plot_gallery_default.html'
    html = page.read_text(encoding='utf-8')
    # Not a vacuous check: the override actually took effect
    assert 'sphx-glr-download-link-note' not in html
    assert 'Download Python source code' in html
    assert 'Download Jupyter notebook' in html

    assert description(html_dir, 'gallery/plot_gallery_default.html') == (
        GALLERY_DEFAULT_DESCRIPTION
    )


@pytest.mark.parametrize('page', ['index.html', 'some_plots.html', 'some_autodocs.html'])
def test_plain_meta_description_matches(html_dir: Path, page: str):
    """The plain ``description`` meta tag says the same thing as ``og:description``."""
    tags = meta_tags(html_dir / page)

    assert tags.get('description') == tags['og:description']


def test_description_can_be_disabled(tmp_path: Path):
    """``autoopengraph_description = False`` leaves ``sphinxext-opengraph`` alone.

    Distinct from disabling ``sphinx_autoopengraph`` entirely: the image half
    stays on, only the description parser turns off.
    """
    html_dir = _build(tmp_path, 'autoopengraph_description = False')

    # Without our own parser, the `desc` node hides the whole docstring
    assert 'og:description' not in meta_tags(html_dir / 'some_autodocs.html')
    # The image half is unaffected
    assert 'og:image' in meta_tags(html_dir / 'some_autodocs.html')


def test_description_requires_sphinxext_opengraph(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """Enabling ``sphinx_autoopengraph`` is a no-op without ``sphinxext.opengraph``.

    Listing ``sphinx_autoopengraph`` is itself the opt-in, so the only way to get
    nothing is to not also enable ``sphinxext.opengraph``.
    """
    for hook in ENVIRONMENT_HOOKS:
        monkeypatch.delenv(hook, raising=False)
    source_dir = copy_tinypages(tmp_path)
    conf = source_dir / 'conf.py'
    conf.write_text(conf.read_text(encoding='utf-8').replace("'sphinxext.opengraph',\n", ''))

    html_dir = tmp_path / 'html'
    returncode, out, err = _run_sphinx_build(
        _sphinx_build_cmd(source_dir, html_dir, tmp_path / 'doctrees'),
    )
    assert returncode == 0, f'sphinx build failed with stdout:\n{out}\nstderr:\n{err}\n'

    # Without PyVista's parser, the ``desc`` node hides the whole docstring
    assert 'og:description' not in meta_tags(html_dir / 'some_autodocs.html')


@pytest.mark.parametrize(
    ('text', 'expected'),
    [
        ('short enough', 'short enough'),
        ('exactly twenty chars', 'exactly twenty chars'),
        # Backs up to a word boundary rather than cutting mid-word
        ('a sentence that runs on and on', 'a sentence that...'),
        # A single long word has no boundary to back up to
        ('supercalifragilisticexpialidocious', 'supercalifragilis...'),
        # Trailing punctuation left dangling by the cut is dropped
        ('one, two, three, four', 'one, two, three...'),
    ],
)
def test_truncate(text: str, expected: str):
    assert _truncate(text, 20) == expected
