"""Tests for tinypages build using pyvista's plot_directive extension."""

from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
from subprocess import PIPE
from subprocess import Popen
import sys

import pytest

from pyvista.plotting import system_supports_plotting
from tests.conftest import flaky_test

pytest.importorskip('sphinx')

# skip all tests if unable to render
if not system_supports_plotting():
    pytestmark = pytest.mark.skip(reason='Requires system to support plotting')


def _filter_suffix(files: set[str], suffix) -> set[str]:
    return {file for file in files if file.endswith(suffix)}


def _sphinx_build_cmd(
    source_dir: Path,
    html_dir: Path,
    doctree_dir: Path | None = None,
    sphinx_args: tuple[str, ...] = (),
) -> list[str]:
    """Create a sphinx-build command."""
    cmd = [
        sys.executable,
        '-msphinx',
        '-W',
        '-b',
        'html',
        *sphinx_args,
    ]

    if doctree_dir is not None:
        cmd.extend(['-d', str(doctree_dir)])

    cmd.extend([str(source_dir), str(html_dir)])

    if sys.platform == 'win32':
        # matplotlib's plot directive fails to render images on Windows CI, resulting in Sphinx
        # warnings that are fatal errors under ``-W``. Seems like a genuine bug with matplotlib
        # and not PyVista, so we ignore the warnings.
        cmd += ['-D', 'suppress_warnings=image.not_readable,download.not_readable']

    return cmd


def _run_sphinx_build(cmd: list[str]) -> tuple[int, str, str]:
    """Run sphinx-build and return returncode, stdout, and stderr."""
    proc = Popen(
        cmd,
        stdout=PIPE,
        stderr=PIPE,
        universal_newlines=True,
        env={**os.environ, 'MPLBACKEND': ''},
        encoding='utf8',
    )
    out, err = proc.communicate()
    return proc.returncode, out, err


ENVIRONMENT_HOOKS = ('PYVISTA_PLOT_SKIP', 'PYVISTA_PLOT_SKIP_OPTIONAL')


# Files generated by matplotlib's plot directive .The counter is incremented inline after PyVista
# plot's counter in serial builds, so its counter value is 19. For parallel builds, PyVista uses a
# hash instead of a counter, so the matplotlib counter value is 1.
_MATPLOTLIB_PLOT_OUTPUT_MAP = {'some_plots-19.png': 'some_plots-1.png'}
MATPLOTLIB_EXPECTED_IMAGES_SERIAL = set(_MATPLOTLIB_PLOT_OUTPUT_MAP.keys())
MATPLOTLIB_EXPECTED_IMAGES_PARALLEL = set(_MATPLOTLIB_PLOT_OUTPUT_MAP.values())

_PYVISTA_PLOT_DIRECTIVE_OUTPUT_MAP = {  # serial : parallel
    'plot_cone.py': 'plot_cone.py',
    'plot_cone_00_00.png': 'plot_cone_00_00.png',
    'plot_polygon.py': 'plot_polygon.py',
    'plot_polygon_00_00.png': 'plot_polygon_00_00.png',
    'plot_polygon_00_00.vtksz': 'plot_polygon_00_00.vtksz',
    'some_autodocs-1.py': 'some_autodocs-8ccebb28d33fc018.py',
    'some_autodocs-1_00_00.png': 'some_autodocs-8ccebb28d33fc018_00_00.png',
    'some_autodocs-1_00_00.vtksz': 'some_autodocs-8ccebb28d33fc018_00_00.vtksz',
    'some_autodocs-2.py': 'some_autodocs-80e223484f96e441.py',
    'some_autodocs-2_00_00.png': 'some_autodocs-80e223484f96e441_00_00.png',
    'some_autodocs-2_00_00.vtksz': 'some_autodocs-80e223484f96e441_00_00.vtksz',
    'some_autodocs-3.py': 'some_autodocs-42ffc56bd5d37b98.py',
    'some_autodocs-4.py': 'some_autodocs-38ff14d651efa596.py',
    'some_plots-1.py': 'some_plots-20cfc06bd259c838.py',
    'some_plots-1_00_00.png': 'some_plots-20cfc06bd259c838_00_00.png',
    'some_plots-1_00_00.vtksz': 'some_plots-20cfc06bd259c838_00_00.vtksz',
    'some_plots-2.py': 'some_plots-b1e1743e65b7e58b.py',
    'some_plots-2_00_00.png': 'some_plots-b1e1743e65b7e58b_00_00.png',
    'some_plots-2_00_00.vtksz': 'some_plots-b1e1743e65b7e58b_00_00.vtksz',
    'some_plots-3.py': 'some_plots-86f4e2ff032281e0.py',
    'some_plots-4.py': 'some_plots-b676d0c7ee8b5705.py',
    'some_plots-4_00_00.png': 'some_plots-b676d0c7ee8b5705_00_00.png',
    'some_plots-4_00_00.vtksz': 'some_plots-b676d0c7ee8b5705_00_00.vtksz',
    'some_plots-5.py': 'some_plots-d9408036e95e4d92.py',
    'some_plots-6.py': 'some_plots-77ca4df61a63cc7e.py',
    'some_plots-7.py': 'some_plots-86f4e2ff032281e0.py',
    'some_plots-8.py': 'some_plots-17ad813bbc871bb4.py',
    'some_plots-8_00_00.png': 'some_plots-17ad813bbc871bb4_00_00.png',
    'some_plots-9.py': 'some_plots-d5403b3be008d1ad.py',
    'some_plots-9_00_00.png': 'some_plots-d5403b3be008d1ad_00_00.png',
    'some_plots-9_01_00.png': 'some_plots-d5403b3be008d1ad_01_00.png',
    'some_plots-10.py': 'some_plots-ab42a22232ee22ac.py',
    'some_plots-11.py': 'some_plots-ab42a22232ee22ac.py',
    'some_plots-12.py': 'some_plots-ab42a22232ee22ac.py',
    'some_plots-13.py': 'some_plots-620986842a31ad95.py',
    'some_plots-13_00_00.png': 'some_plots-620986842a31ad95_00_00.png',
    'some_plots-13_00_00.vtksz': 'some_plots-620986842a31ad95_00_00.vtksz',
    'some_plots-13_01_00.png': 'some_plots-620986842a31ad95_01_00.png',
    'some_plots-13_01_00.vtksz': 'some_plots-620986842a31ad95_01_00.vtksz',
    'some_plots-14.py': 'some_plots-726f2856ca245d20.py',
    'some_plots-14_00_00.png': 'some_plots-726f2856ca245d20_00_00.png',
    'some_plots-14_01_00.png': 'some_plots-726f2856ca245d20_01_00.png',
    'some_plots-15.py': 'some_plots-c235c09f8b7e3f5f.py',
    'some_plots-15_00_00.png': 'some_plots-c235c09f8b7e3f5f_00_00.png',
    'some_plots-15_00_00.vtksz': 'some_plots-c235c09f8b7e3f5f_00_00.vtksz',
    'some_plots-16.py': 'some_plots-80af6225cead2cb6.py',
    'some_plots-16_00_00.png': 'some_plots-80af6225cead2cb6_00_00.png',
    'some_plots-16_00_00.vtksz': 'some_plots-80af6225cead2cb6_00_00.vtksz',
    'some_plots-17.py': 'some_plots-f9e3ea805d5e738f.py',
    'some_plots-18.py': 'some_plots-2e0b60bf8c0e9f87.py',
    'some_plots-18_00_00.png': 'some_plots-2e0b60bf8c0e9f87_00_00.png',
    'some_plots-18_00_00.vtksz': 'some_plots-2e0b60bf8c0e9f87_00_00.vtksz',
    'some_plots-20.py': 'some_plots-42ffc56bd5d37b98.py',
    'some_plots-21.py': 'some_plots-3afe6bf6426295e1.py',
    'some_plots-21_00_00.png': 'some_plots-3afe6bf6426295e1_00_00.png',
    'some_plots-21_00_00.vtksz': 'some_plots-3afe6bf6426295e1_00_00.vtksz',
    'some_plots-22.py': 'some_plots-284b96448f75c72d.py',
    'some_plots-22_00_00.png': 'some_plots-284b96448f75c72d_00_00.png',
    'some_plots-22_00_00.vtksz': 'some_plots-284b96448f75c72d_00_00.vtksz',
    'some_plots-23.py': 'some_plots-a2221791fdc1a8f6.py',
    'some_plots-23_00_00.gif': 'some_plots-a2221791fdc1a8f6_00_00.gif',
    'some_plots-24.py': 'some_plots-7fc6e5a3627f84fa.py',
    'some_plots-24_00_00.png': 'some_plots-7fc6e5a3627f84fa_00_00.png',
    'some_plots-24_00_00.vtksz': 'some_plots-7fc6e5a3627f84fa_00_00.vtksz',
    'some_plots-25.py': 'some_plots-a9e7a9568ee7353a.py',
    'some_plots-25_00_00.png': 'some_plots-a9e7a9568ee7353a_00_00.png',
    'some_plots-25_00_00.vtksz': 'some_plots-a9e7a9568ee7353a_00_00.vtksz',
    'some_plots-26.py': 'some_plots-d6d29e70fc00509a.py',
    'some_plots-26_00_01.png': 'some_plots-d6d29e70fc00509a_00_01.png',
    'some_plots-26_00_01.vtksz': 'some_plots-d6d29e70fc00509a_00_01.vtksz',
}

ALL_EXPECTED_FILES_SERIAL = set(_PYVISTA_PLOT_DIRECTIVE_OUTPUT_MAP.keys())
ALL_EXPECTED_FILES_PARALLEL = set(_PYVISTA_PLOT_DIRECTIVE_OUTPUT_MAP.values())
ALL_EXPECTED_PY_FILES_SERIAL = _filter_suffix(ALL_EXPECTED_FILES_SERIAL, '.py')

IMAGES_NEVER_SKIPPED = {'some_plots-16_00_00.png', 'some_plots-16_00_00.vtksz'}  # Uses :skip: no
IMAGES_OPTIONAL = {'some_plots-18_00_00.png', 'some_plots-18_00_00.vtksz'}  # Uses :optional:


@dataclass(frozen=True)
class TinyPagesCase:
    id: str
    env: dict[str, str]
    expected_files: set[str]
    expected_images_matplotlib: set[str]
    parallel: bool = False
    sphinx_args: tuple[str, ...] = ()

    @property
    def expected_images(self) -> set[str]:
        return (
            _filter_suffix(self.expected_files, '.png')
            | _filter_suffix(self.expected_files, '.gif')
            | _filter_suffix(self.expected_files, '.vtksz')
        )

    @property
    def expected_py_files(self) -> set[str]:
        return _filter_suffix(self.expected_files, '.py')


CASES = (
    TinyPagesCase(
        id='default',
        env={},
        expected_files=ALL_EXPECTED_FILES_SERIAL,
        expected_images_matplotlib=MATPLOTLIB_EXPECTED_IMAGES_SERIAL,
    ),
    TinyPagesCase(
        id='plot_skip_false',
        env={'PYVISTA_PLOT_SKIP': 'false'},
        expected_files=ALL_EXPECTED_FILES_SERIAL,
        expected_images_matplotlib=MATPLOTLIB_EXPECTED_IMAGES_SERIAL,
    ),
    TinyPagesCase(
        id='plot_skip_true',
        env={'PYVISTA_PLOT_SKIP': 'true'},
        expected_files=IMAGES_NEVER_SKIPPED | ALL_EXPECTED_PY_FILES_SERIAL,
        expected_images_matplotlib=MATPLOTLIB_EXPECTED_IMAGES_SERIAL,
    ),
    TinyPagesCase(
        id='plot_skip_optional_true',
        env={'PYVISTA_PLOT_SKIP_OPTIONAL': 'true'},
        expected_files=ALL_EXPECTED_FILES_SERIAL - IMAGES_OPTIONAL,
        expected_images_matplotlib=MATPLOTLIB_EXPECTED_IMAGES_SERIAL,
    ),
    TinyPagesCase(
        id='parallel',
        env={'PYVISTA_PLOT_USE_COUNTER': 'false'},
        expected_files=ALL_EXPECTED_FILES_PARALLEL,
        expected_images_matplotlib=MATPLOTLIB_EXPECTED_IMAGES_PARALLEL,
        parallel=True,
        sphinx_args=('-j2',),
    ),
)


@flaky_test(exceptions=(AssertionError,))
@pytest.mark.parametrize('case', CASES, ids=lambda case: case.id)
def test_tinypages(tmp_path: Path, case: TinyPagesCase, monkeypatch: pytest.MonkeyPatch):
    """Test tinypages build using pyvista's plot_directive extension."""
    for hook in ENVIRONMENT_HOOKS:
        monkeypatch.delenv(hook, raising=False)
    for key, value in case.env.items():
        monkeypatch.setenv(key, value)

    skip = case.env.get('PYVISTA_PLOT_SKIP', 'false').lower() == 'true'
    skip_optional = case.env.get('PYVISTA_PLOT_SKIP_OPTIONAL', 'false').lower() == 'true'
    expected = not skip
    expected_optional = False if skip else not skip_optional

    source_dir = Path(__file__).parent / 'tinypages'
    html_dir = tmp_path / 'html'
    doctree_dir = tmp_path / 'doctrees'

    returncode, out, err = _run_sphinx_build(
        _sphinx_build_cmd(
            source_dir,
            html_dir,
            doctree_dir,
            case.sphinx_args,
        ),
    )
    assert returncode == 0, f'sphinx build failed with stdout:\n{out}\nstderr:\n{err}\n'

    assert html_dir.is_dir()

    # All files are saved to the pyvista plot dir
    pyvista_plot_directive_dir = html_dir.parent / 'pyvista_plot_directive'
    pyvista_plot_directive_files = {path.name for path in pyvista_plot_directive_dir.iterdir()}
    assert pyvista_plot_directive_files == case.expected_files

    # Ensure all generated Python files can be compiled
    non_compilable_files = set()
    for file in case.expected_py_files:
        path = pyvista_plot_directive_dir / file
        try:
            compile(path.read_text(encoding='utf-8'), str(path), 'exec')
        except SyntaxError:
            non_compilable_files.add(file)
    non_compilable = '\n'.join(sorted(non_compilable_files))
    assert not non_compilable_files, f'Non-compilable Python files: \n{non_compilable}'

    # Ensure no copies are saved to the html dir itself
    unexpected_files = [
        path for ext in ('py', 'rst', 'png', 'vtksz') for path in html_dir.glob(f'*.{ext}')
    ]
    assert not unexpected_files, f'Unexpected files in html dir: {unexpected_files}'

    # Sphinx auto-copies to `_images`. Expect matplotlib's directive output to exist as well
    images_dir = html_dir / '_images'
    actual_html_images = {p.name for p in images_dir.rglob('*') if p.is_file()}

    if sys.platform == 'win32':
        # Bug with matplotlib not generating files on Windows. Assert the expected files don't
        # exist, then patch the output to pretend like they exist to work around this bug
        assert not (case.expected_images_matplotlib & actual_html_images), (
            "matplotlib's plot unexpectedly rendered on Windows, "
            'the workaround below can likely be removed.'
        )
        for missing in case.expected_images_matplotlib:
            (images_dir / missing).touch()
        actual_html_images = {p.name for p in images_dir.rglob('*') if p.is_file()}

    expected_images = case.expected_images | case.expected_images_matplotlib
    assert actual_html_images == expected_images

    html_contents = (html_dir / 'some_plots.html').read_bytes()

    assert b'# Only a comment' in html_contents

    # check if figure caption made it into html file
    assert (b'This is the caption for plot 8.' in html_contents) == expected

    # check if figure caption using :caption: made it into html file
    assert (b'Plot 8 uses the caption option.' in html_contents) == expected

    # check that the multi-image caption is applied twice
    assert (html_contents.count(b'This caption applies to both plots.') == 2) == expected

    assert b'you should not be reading this right now' not in html_contents
    assert b'should be printed: include-source with no args' in html_contents

    # check that caption with tabs works
    assert (
        html_contents.count(b'Plot 15 uses the caption option with tabbed UI.') == 1
    ) == expected

    # check that no skip always exists
    assert b'Plot 16 will never be skipped' in html_contents

    # check that enforced skip caption doesn't exist
    assert b'This plot will always be skipped with no caption' not in html_contents

    # check conditional execution
    assert (b'This plot may be skipped with no caption' in html_contents) == expected_optional

    # check matplotlib plot exists
    assert b'This is a matplotlib plot.' in html_contents


@flaky_test(exceptions=(AssertionError,))
def test_parallel_error(tmp_path: Path) -> None:
    """Ensure that labeling image serial fails."""
    source_dir = Path(__file__).parent / 'tinypages'
    html_dir = tmp_path / 'html'
    doctree_dir = tmp_path / 'doctrees'

    returncode, _, err = _run_sphinx_build(
        _sphinx_build_cmd(
            source_dir,
            html_dir,
            doctree_dir,
            ('-j2',),
        ),
    )

    assert returncode != 0
    assert 'pyvista_plot_use_counter' in err
    assert 'cannot be enabled for parallel builds' in err


@flaky_test(exceptions=(AssertionError,))
def test_tinypages_download_examples_integration(tmp_path: Path):
    """Check that the ``download_examples`` extension is wired into the real docs build."""
    source_dir = Path(__file__).parent / 'tinypages'
    html_dir = tmp_path / 'html'
    doctree_dir = tmp_path / 'doctrees'

    returncode, out, err = _run_sphinx_build(
        _sphinx_build_cmd(source_dir, html_dir, doctree_dir),
    )
    assert returncode == 0, f'sphinx build failed with stdout:\n{out}\nstderr:\n{err}\n'

    downloads_dir = html_dir / '_downloads'
    assert downloads_dir.is_dir(), 'expected examples_download to produce a _downloads dir'

    generated_names = {p.name for p in downloads_dir.rglob('*.py')}
    samples_names = {name for name in generated_names if name.startswith('samples_')}

    # samples includes four functions with Examples docstrings, so we should expect four
    # downloads, but make_sphere_second uses ``:include-source: False``, so a download is
    # not generated
    expected_names = {
        'samples_make_sphere.py',
        'samples_example_with_empty_plotter.py',
        'samples_example_with_closed_plotter.py',
    }
    assert samples_names == expected_names, (
        f'expected downloads for {expected_names}, got {samples_names}'
    )

    some_autodocs_html = (html_dir / 'some_autodocs.html').read_text(encoding='utf-8')
    assert some_autodocs_html.count('reference download') == len(expected_names)


@pytest.mark.needs_playwright
def test_interactive_plot_moves(tmp_path: Path):
    from http.server import SimpleHTTPRequestHandler
    from http.server import ThreadingHTTPServer
    from threading import Thread

    from playwright.sync_api import sync_playwright

    source_dir = Path(__file__).parent / 'tinypages'
    html_dir = tmp_path / '_build'

    returncode, out, err = _run_sphinx_build(
        _sphinx_build_cmd(source_dir, html_dir),
    )
    assert returncode == 0, f'sphinx build failed with stdout:\n{out}\nstderr:\n{err}\n'

    old_cwd = Path.cwd()
    os.chdir(html_dir)

    server = ThreadingHTTPServer(('127.0.0.1', 0), SimpleHTTPRequestHandler)
    thread = Thread(target=server.serve_forever, daemon=True)
    thread.start()

    try:
        with sync_playwright() as p:
            # Open docs in browser
            browser = p.chromium.launch()
            page = browser.new_page()

            host, port = server.server_address
            page.goto(f'http://{host}:{port}/some_plots.html')
            page.wait_for_timeout(1000)

            # Navigate to interactive scene tab
            page.get_by_text('Interactive Scene', exact=True).first.click()
            page.wait_for_timeout(1000)

            frame = page.frame_locator('iframe').first
            canvas = frame.locator('canvas')

            canvas.wait_for(timeout=10000)

            # Simulate interacting with the scene, taking a screenshot before and after
            before = canvas.screenshot()

            box = canvas.bounding_box()
            assert box is not None

            x = box['x'] + box['width'] / 2
            y = box['y'] + box['height'] / 2

            page.mouse.move(x, y)
            page.mouse.down()
            page.mouse.move(x + 200, y + 100)
            page.mouse.up()

            page.wait_for_timeout(500)

            after = canvas.screenshot()

            # Interaction is successful if screenshot differs
            assert before != after

    finally:
        server.shutdown()
        server.server_close()
        os.chdir(old_cwd)
