name: Bug Report
description: Create a report to help us fix broken features
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to open this issue to help improve PyVista!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug, what's wrong, and what you expected.
      description: |
        Provide a clear and concise description of what the bug is.
        Provide a clear and concise description of what you expected to happen.
      placeholder: Tell us what you see!
      value: "I found a bug!"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the bug.
      description: |
        Please provide a list of steps to reproduce the bug.
        Please include a code snippet to reproduce the bug in the text box below.
      placeholder: Provide some code for us to reproduce the bug!
      value: "```python\nInsert code here\n```"
    validations:
      required: true
  - type: textarea
    id: system-information
    attributes:
      label: System Information
      placeholder: The log will automatically be formatted! No need to type backticks.
      description: |
        Please run the following wherever you are experiencing the bug, and paste the output below.
        This report helps us track down bugs and will be critical to addressing your bug.

        With python code (e.g. inside IPython or Jupyter Notebook):

        ```python
        # Get system info
        import pyvista as pv
        print(pv.Report())
        ```

        Or with a shell command (requires `pyvista>=0.47`):

        ``` shell
        pyvista report
        ```
      render: shell
    validations:
      required: true
  - type: textarea
    id: dataset-information
    attributes:
      label: Dataset Information
      description: |
        If a custom dataset is needed to reproduce the bug, upload the dataset here or provide a download link.
        In addition, use the `validate_mesh` filter on it and paste the output below.

        For a dataset 'file.vtk', run python code:

        ```python
        import pyvista as pv
        mesh = pv.read('file.vtk')
        print(mesh.validate_mesh())
        ```

        Or with a shell command (requires `pyvista>=0.48`):

        ```shell
        pyvista validate file.vtk
        ```
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please add screenshots to the text box below
