"""Utilities routines."""
from .common import perlin_noise, sample_function
from .errors import (
    GPUInfo,
    Observer,
    Report,
    assert_empty_kwargs,
    get_gpu_info,
    send_errors_to_logging,
    set_error_output_file,
    check_valid_vector,
    VtkErrorCatcher,
)
from .features import (
    create_grid,
    grid_from_sph_coords,
    merge,
    transform_vectors_sph_to_cart,
    voxelize,
)
from .fileio import (
    from_meshio,
    get_ext,
    read_exodus,
    read_legacy,
    read_meshio,
    read_plot3d,
    read_texture,
    read,
    save_meshio,
    set_vtkwriter_mode,
)
from .geometric_objects import (
    Arrow,
    Box,
    Circle,
    CircularArcFromNormal,
    CircularArc,
    Cone,
    Cube,
    CylinderStructured,
    Cylinder,
    Disc,
    Dodecahedron,
    Ellipse,
    Icosahedron,
    Line,
    MultipleLines,
    NORMALS,
    Octahedron,
    Plane,
    PlatonicSolid,
    Polygon,
    Pyramid,
    Rectangle,
    Sphere,
    Superquadric,
    Tetrahedron,
    Text3D,
    translate,
    Triangle,
    Tube,
    Wavelet,
)
from .helpers import (
    AmbiguousDataError,
    FieldAssociation,
    MissingDataError,
    ProgressMonitor,
    abstract_class,
    array_from_vtkmatrix,
    axis_rotation,
    cell_array,
    check_depth_peeling,
    conditional_decorator,
    convert_array,
    convert_string_array,
    cubemap_from_filenames,
    cubemap,
    field_array,
    fit_plane_to_points,
    generate_plane,
    get_array_association,
    get_array,
    get_vtk_type,
    image_to_texture,
    is_inside_bounds,
    is_meshio_mesh,
    is_pyvista_dataset,
    line_segments_from_points,
    lines_from_points,
    make_tri_mesh,
    numpy_to_texture,
    parse_field_choice,
    point_array,
    raise_not_matching,
    row_array,
    set_default_active_scalars,
    set_default_active_vectors,
    threaded,
    trans_from_matrix,
    try_callback,
    vector_poly_data,
    vtk_bit_array_to_char,
    vtk_id_list_to_array,
    vtkmatrix_from_array,
    vtk_points,
    wrap,
)
from .misc import (
    PyVistaDeprecationWarning,
    _get_vtk_id_type,
    _set_plot_theme_from_env,
    set_pickle_format,
    vtk_version_info,
)
from .parametric_objects import (
    KochanekSpline,
    ParametricBohemianDome,
    ParametricBour,
    ParametricBoy,
    ParametricCatalanMinimal,
    ParametricConicSpiral,
    ParametricCrossCap,
    ParametricDini,
    ParametricEllipsoid,
    ParametricEnneper,
    ParametricFigure8Klein,
    ParametricHenneberg,
    parametric_keywords,
    ParametricKlein,
    ParametricKuen,
    ParametricMobius,
    ParametricPluckerConoid,
    ParametricPseudosphere,
    ParametricRandomHills,
    ParametricRoman,
    ParametricSuperEllipsoid,
    ParametricSuperToroid,
    ParametricTorus,
    Spline,
    surface_from_para,
)
from .sphinx_gallery import Scraper, _get_sg_image_scraper
from .regression import compare_images
from . import transformations
from .xvfb import start_xvfb
from .reader import (
    get_reader,
    AVSucdReader,
    BaseReader,
    BinaryMarchingCubesReader,
    BMPReader,
    BYUReader,
    CGNSReader,
    DEMReader,
    EnSightReader,
    FacetReader,
    FluentReader,
    GIFReader,
    GLTFReader,
    HDFReader,
    HDRReader,
    JPEGReader,
    MetaImageReader,
    MFIXReader,
    MultiBlockPlot3DReader,
    NIFTIReader,
    NRRDReader,
    OBJReader,
    OpenFOAMReader,
    POpenFOAMReader,
    Plot3DFunctionEnum,
    Plot3DMetaReader,
    PLYReader,
    PNGReader,
    PNMReader,
    PointCellDataSelection,
    PTSReader,
    PVDDataSet,
    PVDReader,
    SegYReader,
    SLCReader,
    STLReader,
    TecplotReader,
    TIFFReader,
    TimeReader,
    VTKDataSetReader,
    VTKPDataSetReader,
    XMLImageDataReader,
    XMLPImageDataReader,
    XMLRectilinearGridReader,
    XMLPRectilinearGridReader,
    XMLUnstructuredGridReader,
    XMLPUnstructuredGridReader,
    XMLPolyDataReader,
    XMLStructuredGridReader,
    XMLMultiBlockDataReader,
    DICOMReader,
)

# __all__ only left for mypy --strict to work when pyvista is a dependency
__all__ = [
    # submodules:
    # 'arrays',
    # 'cells',
    # 'common',
    # 'errors',
    # 'features',
    'fileio',
    # 'geometric_objects',
    # 'helpers',
    # 'misc',
    # 'parametric_objects',
    'reader',
    # 'regression',
    # 'sphinx_gallery',
    'transformations',
    # 'wrappers',
    # 'xvfb',
    # common:
    'perlin_noise',
    'sample_function',
    # errors:
    'GPUInfo',
    'Observer',
    'Report',
    'VtkErrorCatcher',
    'assert_empty_kwargs',
    'check_valid_vector',
    'get_gpu_info',
    'send_errors_to_logging',
    'set_error_output_file',
    # features:
    'create_grid',
    'grid_from_sph_coords',
    'merge',
    'transform_vectors_sph_to_cart',
    'voxelize',
    # fileio:
    'from_meshio',
    'get_ext',
    'read_exodus',
    'read_legacy',
    'read_meshio',
    'read_plot3d',
    'read_texture',
    'read',
    'save_meshio',
    'set_vtkwriter_mode',
    # geometric_objects:
    'Arrow',
    'Box',
    'Circle',
    'CircularArcFromNormal',
    'CircularArc',
    'Cone',
    'Cube',
    'CylinderStructured',
    'Cylinder',
    'Disc',
    'Dodecahedron',
    'Ellipse',
    'Icosahedron',
    'Line',
    'MultipleLines',
    'NORMALS',
    'Octahedron',
    'Plane',
    'PlatonicSolid',
    'Polygon',
    'Pyramid',
    'Rectangle',
    'Sphere',
    'Superquadric',
    'Tetrahedron',
    'Text3D',
    'translate',
    'Triangle',
    'Tube',
    'Wavelet',
    # helpers:
    'AmbiguousDataError',
    'FieldAssociation',
    'MissingDataError',
    'ProgressMonitor',
    'abstract_class',
    'array_from_vtkmatrix',
    'axis_rotation',
    'cell_array',
    'check_depth_peeling',
    'conditional_decorator',
    'convert_array',
    'convert_string_array',
    'cubemap_from_filenames',
    'cubemap',
    'field_array',
    'fit_plane_to_points',
    'generate_plane',
    'get_array_association',
    'get_array',
    'get_vtk_type',
    'image_to_texture',
    'is_inside_bounds',
    'is_meshio_mesh',
    'is_pyvista_dataset',
    'line_segments_from_points',
    'lines_from_points',
    'make_tri_mesh',
    'numpy_to_texture',
    'parse_field_choice',
    'point_array',
    'raise_not_matching',
    'row_array',
    'set_default_active_scalars',
    'set_default_active_vectors',
    'threaded',
    'trans_from_matrix',
    'try_callback',
    'vector_poly_data',
    'vtk_bit_array_to_char',
    'vtk_id_list_to_array',
    'vtkmatrix_from_array',
    'vtk_points',
    'wrap',
    # misc:
    'PyVistaDeprecationWarning',
    '_get_vtk_id_type',
    '_set_plot_theme_from_env',
    'set_pickle_format',
    'vtk_version_info',
    # parametric_objects:
    'KochanekSpline',
    'ParametricBohemianDome',
    'ParametricBour',
    'ParametricBoy',
    'ParametricCatalanMinimal',
    'ParametricConicSpiral',
    'ParametricCrossCap',
    'ParametricDini',
    'ParametricEllipsoid',
    'ParametricEnneper',
    'ParametricFigure8Klein',
    'ParametricHenneberg',
    'parametric_keywords',
    'ParametricKlein',
    'ParametricKuen',
    'ParametricMobius',
    'ParametricPluckerConoid',
    'ParametricPseudosphere',
    'ParametricRandomHills',
    'ParametricRoman',
    'ParametricSuperEllipsoid',
    'ParametricSuperToroid',
    'ParametricTorus',
    'Spline',
    'surface_from_para',
    # reader:
    'AVSucdReader',
    'BaseReader',
    'BinaryMarchingCubesReader',
    'BMPReader',
    'BYUReader',
    'CGNSReader',
    'DEMReader',
    'DICOMReader',
    'EnSightReader',
    'FacetReader',
    'FluentReader',
    'get_reader',
    'GIFReader',
    'GLTFReader',
    'HDFReader',
    'HDRReader',
    'JPEGReader',
    'MetaImageReader',
    'MFIXReader',
    'MultiBlockPlot3DReader',
    'NIFTIReader',
    'NRRDReader',
    'OBJReader',
    'OpenFOAMReader',
    'Plot3DFunctionEnum',
    'Plot3DMetaReader',
    'PLYReader',
    'PNGReader',
    'PNMReader',
    'PointCellDataSelection',
    'POpenFOAMReader',
    'PTSReader',
    'PVDDataSet',
    'PVDReader',
    'SegYReader',
    'SLCReader',
    'STLReader',
    'TecplotReader',
    'TIFFReader',
    'TimeReader',
    'VTKDataSetReader',
    'VTKPDataSetReader',
    'XMLImageDataReader',
    'XMLMultiBlockDataReader',
    'XMLPImageDataReader',
    'XMLPolyDataReader',
    'XMLPRectilinearGridReader',
    'XMLPUnstructuredGridReader',
    'XMLRectilinearGridReader',
    'XMLStructuredGridReader',
    'XMLUnstructuredGridReader',
    # regression:
    'compare_images',
    # sphinx_gallery:
    'Scraper',
    # needs to be available in top namespace per contract with Sphinx-Gallery:
    '_get_sg_image_scraper',
    # xvfb:
    'start_xvfb',
]
