"""Test the built contributing page."""

from __future__ import annotations

from pathlib import Path

from conftest import HTML_DIR


def test_contributing_edit_button_points_to_contributing():
    """Confirm the page's edit button links to CONTRIBUTING.rst, not an autogenerated copy."""
    html = (Path(HTML_DIR) / 'contributing.html').read_text(encoding='utf-8')
    assert 'https://github.com/pyvista/pyvista/edit/main/CONTRIBUTING.rst' in html
