"""Route every class member to exactly one autosummary page.

``autosummary``'s class template can only ask whether a member is inherited, not
*where* it is documented, so ``_templates/autosummary/class.rst`` used to drop every
inherited member. Members whose defining class is not itself documented -- private
bases such as ``_PointSet`` and internal ones such as ``Grid`` or ``BasePlotter`` --
were therefore dropped everywhere, and the workaround (documenting every member of
``ImageData``, ``DataSetMapper`` and ``Plotter``) duplicated hundreds of pages and
pulled in pure-VTK members that raise on access.

This module answers the question the template actually needs: for a member reachable
on a class, which documented class owns its page? That is the *most basal* documented
class in the MRO providing the same implementation, falling back to the class itself
when every provider is undocumented. Members implemented by VTK are never documented.
"""

from __future__ import annotations

import functools
import importlib
import inspect
from pathlib import Path
import re
from typing import TYPE_CHECKING
from typing import Any

if TYPE_CHECKING:
    from collections.abc import Iterable
    from collections.abc import Sequence

    from sphinx.application import Sphinx

_AUTOSUMMARY_RE = re.compile(r'^(\s*)\.\.\s+autosummary::\s*$')
_TOCTREE_RE = re.compile(r'^\s+:toctree:')
_OPTION_RE = re.compile(r'^\s+:')
_ITEM_RE = re.compile(r'^\s+(~?[_a-zA-Z][a-zA-Z0-9_.]*)\s*$')
_MODULE_RE = re.compile(r'^\s*\.\.\s+(?:current)?module::\s*([a-zA-Z0-9_.]+)\s*$')

#: Set by :func:`setup`; the helpers below are called from Jinja and get nothing else.
_srcdir: Path | None = None

#: ``{class: dotted name it is documented under}``, built lazily from the doc sources.
_documented: dict[type, str] | None = None


def _scan(text: str) -> set[str]:
    """Return the fully qualified names of every page-generating autosummary entry."""
    names: set[str] = set()
    current_module = ''
    in_autosummary = False
    has_toctree = False
    pending: list[str] = []
    base_indent = ''

    def flush() -> None:
        if has_toctree:
            names.update(pending)
        pending.clear()

    for line in text.splitlines():
        if in_autosummary:
            if _TOCTREE_RE.match(line):
                has_toctree = True
                continue
            if _OPTION_RE.match(line):
                continue
            if item := _ITEM_RE.match(line):
                name = item.group(1).removeprefix('~')
                if current_module and not name.startswith(current_module + '.'):
                    name = f'{current_module}.{name}'
                pending.append(name)
                continue
            if not line.strip() or line.startswith(base_indent + ' '):
                continue
            flush()
            in_autosummary = False

        if match := _AUTOSUMMARY_RE.match(line):
            flush()
            in_autosummary = True
            has_toctree = False
            base_indent = match.group(1)
        elif match := _MODULE_RE.match(line):
            current_module = match.group(1)
    flush()
    return names


def _resolve(name: str) -> Any:
    """Import ``name``, walking back through its dotted path until something imports."""
    parts = name.split('.')
    for split in range(len(parts), 0, -1):
        try:
            obj = importlib.import_module('.'.join(parts[:split]))
        except ImportError:
            continue
        for part in parts[split:]:
            try:
                obj = getattr(obj, part)
            except AttributeError:
                return None
        return obj
    return None


def _documented_classes() -> dict[type, str]:
    """Return ``{class: dotted name}`` for every class with an autosummary page."""
    global _documented  # noqa: PLW0603
    if _documented is not None:
        return _documented
    if _srcdir is None:
        msg = 'The pyvista.ext._autoinherit extension is not loaded.'
        raise RuntimeError(msg)

    classes: dict[type, str] = {}
    for path in sorted(_srcdir.rglob('*.rst')):
        if '_autosummary' in path.parts or '_templates' in path.parts:
            continue  # generated by, or an input to, autosummary itself
        for name in sorted(_scan(path.read_text(encoding='utf-8', errors='replace'))):
            obj = _resolve(name)
            if isinstance(obj, type):
                classes.setdefault(obj, name)
    _documented = classes
    return classes


@functools.cache
def _provider(cls: type, member: str) -> type | None:
    """Return the class in ``cls``'s MRO whose body defines ``member``."""
    for base in cls.__mro__:
        if member in base.__dict__:
            return base
    # A bare annotation -- a dataclass field, say -- defines a member without binding
    # anything, so it is only reachable this way. Real bindings still win, so a subclass
    # that re-annotates an inherited member does not claim it.
    return next((base for base in cls.__mro__ if member in inspect.get_annotations(base)), None)


def _home(cls: type, member: str) -> type | None:
    """Return the documented class owning ``member``'s page, or ``None`` if it has none."""
    provider = _provider(cls, member)
    if provider is None or not provider.__module__.startswith('pyvista'):
        return None  # implemented by VTK or the standard library
    documented = _documented_classes()
    home = cls
    for base in cls.__mro__:  # most derived first, so the last match is the most basal
        if base in documented and _provider(base, member) is provider:
            home = base
    return home


def _candidates(names: Iterable[str]) -> list[str]:
    """Drop the members no class page documents, whichever class they are reached on."""
    return [name for name in names if not name.startswith('_') and not name[0].isupper()]


def _class_from(module: str, objname: str) -> type:
    """Return the class ``class.rst`` is being rendered for."""
    cls = _resolve(f'{module}.{objname}')
    if not isinstance(cls, type):
        msg = f'{module}.{objname} is not a class.'
        raise TypeError(msg)
    return cls


def own_members(  # numpydoc ignore=RT01
    module: str, objname: str, names: Sequence[str]
) -> list[str]:
    """Return the members of ``module.objname`` whose page belongs to it."""
    cls = _class_from(module, objname)
    return [name for name in _candidates(names) if _home(cls, name) is cls]


def inherited_member_groups(  # numpydoc ignore=RT01
    module: str, objname: str, names: Sequence[str]
) -> list[tuple[str, str, list[str]]]:
    """Return ``[(module, class, [members])]`` for the pages ``module.objname`` links to.

    The module is split out so the template can set ``currentmodule`` to it: each summary
    line is the first line of a docstring written for the home class's page, and any
    reference it makes relative to that module only resolves under it.
    """
    cls = _class_from(module, objname)
    documented = _documented_classes()
    groups: dict[type, list[str]] = {}
    for name in _candidates(names):
        home = _home(cls, name)
        if home is not None and home is not cls:
            groups.setdefault(home, []).append(name)
    order = {base: index for index, base in enumerate(cls.__mro__)}
    return [
        (*documented[home].rsplit('.', 1), sorted(groups[home]))
        for home in sorted(groups, key=lambda base: order[base])
    ]


def setup(app: Sphinx) -> dict[str, Any]:  # numpydoc ignore=RT01
    """Record the source directory the documented-class registry is built from."""
    global _srcdir  # noqa: PLW0603
    _srcdir = Path(app.srcdir)
    return {'parallel_read_safe': True, 'parallel_write_safe': True}
