"""Route every class member to exactly one autosummary page.

``autosummary``'s class template can only ask whether a member is inherited, not
*where* it is documented, so ``_templates/autosummary/class.rst`` used to drop every
inherited member. Members whose defining class is not itself documented -- private
bases such as ``_PointSetBase`` and internal ones such as ``Grid`` or ``BasePlotter`` --
were therefore dropped everywhere, and the workaround (documenting every member of
``ImageData``, ``DataSetMapper`` and ``Plotter``) duplicated hundreds of pages and
pulled in pure-VTK members that raise on access.

This module answers the question the template actually needs: for a member reachable
on a class, which documented class owns its page? That is the *most basal* documented
class in the MRO providing the same implementation, falling back to the class itself
when every provider is undocumented. Members implemented by VTK are never documented.
"""

from __future__ import annotations

import functools
import importlib
import inspect
from pathlib import Path
import re
from typing import TYPE_CHECKING
from typing import Any

from docutils.frontend import get_default_settings
from docutils.parsers.rst import Parser
from docutils.utils import new_document
import sphinx
from sphinx.ext.autosummary import extract_summary
from sphinx.util import logging
from sphinx.util.docstrings import prepare_docstring

if TYPE_CHECKING:
    from collections.abc import Iterable
    from collections.abc import Sequence

    from sphinx.application import Sphinx

_AUTOSUMMARY_RE = re.compile(r'^(\s*)\.\.\s+autosummary::\s*$')
_TOCTREE_RE = re.compile(r'^\s+:toctree:')
_OPTION_RE = re.compile(r'^\s+:')
_ITEM_RE = re.compile(r'^\s+(~?[_a-zA-Z][a-zA-Z0-9_.]*)\s*$')
_MODULE_RE = re.compile(r'^\s*\.\.\s+(?:current)?module::\s*([a-zA-Z0-9_.]+)\s*$')

logger = logging.getLogger(__name__)

#: ``provider.member`` for each non-method reachable on a filter class; a new one is reported.
_NOT_API_ON_FILTERS = frozenset({'DataObjectFilters.points', '_BoundsSizeMixin.bounds_size'})

#: Set by :func:`setup`; the helpers below are called from Jinja and get nothing else.
_srcdir: Path | None = None

#: ``{class: dotted name it is documented under}``, built lazily from the doc sources.
_documented: dict[type, str] | None = None


def _scan(text: str) -> set[str]:
    """Return the fully qualified names of every page-generating autosummary entry."""
    names: set[str] = set()
    current_module = ''
    in_autosummary = False
    has_toctree = False
    pending: list[str] = []
    base_indent = ''

    def flush() -> None:
        if has_toctree:
            names.update(pending)
        pending.clear()

    for line in text.splitlines():
        if in_autosummary:
            if _TOCTREE_RE.match(line):
                has_toctree = True
                continue
            if _OPTION_RE.match(line):
                continue
            if item := _ITEM_RE.match(line):
                name = item.group(1).removeprefix('~')
                if current_module and not name.startswith(current_module + '.'):
                    name = f'{current_module}.{name}'
                pending.append(name)
                continue
            if not line.strip() or line.startswith(base_indent + ' '):
                continue
            flush()
            in_autosummary = False

        if match := _AUTOSUMMARY_RE.match(line):
            flush()
            in_autosummary = True
            has_toctree = False
            base_indent = match.group(1)
        elif match := _MODULE_RE.match(line):
            current_module = match.group(1)
    flush()
    return names


def _resolve(name: str) -> Any:
    """Import ``name``, walking back through its dotted path until something imports."""
    parts = name.split('.')
    for split in range(len(parts), 0, -1):
        try:
            obj = importlib.import_module('.'.join(parts[:split]))
        except ImportError:
            continue
        for part in parts[split:]:
            try:
                obj = getattr(obj, part)
            except AttributeError:
                return None
        return obj
    return None


def _documented_classes() -> dict[type, str]:
    """Return ``{class: dotted name}`` for every class with an autosummary page."""
    global _documented  # noqa: PLW0603
    if _documented is not None:
        return _documented
    if _srcdir is None:
        msg = 'The pyvista.ext._autoinherit extension is not loaded.'
        raise RuntimeError(msg)

    classes: dict[type, str] = {}
    for path in sorted(_srcdir.rglob('*.rst')):
        if '_autosummary' in path.parts or '_templates' in path.parts:
            continue  # generated by, or an input to, autosummary itself
        for name in sorted(_scan(path.read_text(encoding='utf-8', errors='replace'))):
            obj = _resolve(name)
            if isinstance(obj, type):
                classes.setdefault(obj, name)
    _documented = classes
    return classes


@functools.cache
def _provider(cls: type, member: str) -> type | None:
    """Return the class in ``cls``'s MRO whose body defines ``member``."""
    for base in cls.__mro__:
        if member in base.__dict__:
            return base
    # A bare annotation -- a dataclass field, say -- defines a member without binding
    # anything, so it is only reachable this way. Real bindings still win, so a subclass
    # that re-annotates an inherited member does not claim it.
    return next((base for base in cls.__mro__ if member in inspect.get_annotations(base)), None)


def _is_filter(cls: type) -> bool:
    """Return whether ``cls`` is one of the filter classes datasets mix in."""
    return cls.__module__.startswith('pyvista.core.filters')


@functools.cache
def _warn_unexpected_filter_member(cls: type, member: str) -> None:
    """Report a filter-class member that is dropped without being on the allow list."""
    name = f'{cls.__qualname__}.{member}'
    if name in _NOT_API_ON_FILTERS:
        return
    logger.warning(
        '%s is not a method, so it is documented nowhere. Filter classes are documented '
        'as filters: move it to the class it belongs on, or add it to '
        '_NOT_API_ON_FILTERS in pyvista/ext/_autoinherit.py if it is a typing aid.',
        name,
        type='autoinherit',
    )


def _home(cls: type, member: str) -> type | None:
    """Return the documented class owning ``member``'s page, or ``None`` if it has none."""
    provider = _provider(cls, member)
    if provider is None or not provider.__module__.startswith('pyvista'):
        return None  # implemented by VTK or the standard library
    if not inspect.isroutine(provider.__dict__.get(member)) and (
        _is_filter(provider) or _is_filter(cls)
    ):
        _warn_unexpected_filter_member(provider, member)
        return None
    documented = _documented_classes()
    home = cls
    for base in cls.__mro__:  # most derived first, so the last match is the most basal
        if base in documented and _provider(base, member) is provider:
            home = base
    return home


def _candidates(names: Iterable[str]) -> list[str]:
    """Drop the members no class page documents, whichever class they are reached on."""
    return [name for name in names if not name.startswith('_') and not name[0].isupper()]


def _class_from(module: str, objname: str) -> type:
    """Return the class ``class.rst`` is being rendered for."""
    cls = _resolve(f'{module}.{objname}')
    if not isinstance(cls, type):
        msg = f'{module}.{objname} is not a class.'
        raise TypeError(msg)
    return cls


def own_members(  # numpydoc ignore=RT01
    module: str, objname: str, names: Sequence[str]
) -> list[str]:
    """Return the members of ``module.objname`` whose page belongs to it."""
    cls = _class_from(module, objname)
    return [name for name in _candidates(names) if _home(cls, name) is cls]


@functools.cache
def _summary_document() -> Any:  # numpydoc ignore=RT01
    """Return bare settings on Sphinx 9, else a throwaway document, for ``extract_summary``."""
    settings = get_default_settings(Parser)
    if sphinx.version_info >= (9,):
        return settings
    return new_document('', settings)


def _summary(cls: type, member: str) -> str:
    """Return the summary ``autosummary`` would show for ``cls.member``."""
    provider = _provider(cls, member)
    # Read the descriptor out of the class body rather than with getattr, which would
    # evaluate a property and lose the docstring that produced it.
    obj = provider.__dict__.get(member) if provider is not None else None
    if obj is None:
        return ''
    doc = getattr(obj, '__doc__', None)
    # An instance reports its type's docstring as its own, so a plain class attribute
    # would be summarised with, say, all of `int`'s. Only take a docstring it owns.
    if not doc or doc == getattr(type(obj), '__doc__', None):
        return ''
    doc = inspect.getdoc(obj) or ''
    summary = ' '.join(extract_summary(prepare_docstring(doc), _summary_document()).split())
    # The summary is dropped straight into a list-table cell, where an unescaped pipe
    # would read as a substitution reference. Roles and literals are left to render.
    return summary.replace('|', r'\|')


def _rows(module: str, objname: str, names: Sequence[str]) -> list[tuple[type, str, str, str]]:
    """Return ``[(home, label, target, summary)]``, sorted by member name."""
    cls = _class_from(module, objname)
    documented = _documented_classes()
    rows: list[tuple[str, type, str, str, str]] = []
    for name in _candidates(names):
        home = _home(cls, name)
        if home is None or home is cls:
            continue
        full = documented[home]
        label = f'{full.rsplit(".", 1)[1]}.{name}'
        rows.append((name, home, label, f'{full}.{name}', _summary(home, name)))
    return [row[1:] for row in sorted(rows, key=lambda row: row[0])]


def inherited_member_rows(  # numpydoc ignore=RT01
    module: str, objname: str, names: Sequence[str]
) -> list[tuple[str, str, str]]:
    """Return ``[(label, target, summary)]`` for members documented on another class.

    Filters are left out; they outnumber everything else and get their own section.
    """
    if _is_filter(_class_from(module, objname)):
        return []  # a filter class page lists only the filters it defines
    return [row[1:] for row in _rows(module, objname, names) if not _is_filter(row[0])]


def filter_member_rows(  # numpydoc ignore=RT01
    module: str, objname: str, names: Sequence[str]
) -> list[tuple[str, str, str]]:
    """Return ``[(label, target, summary)]`` for the filters ``module.objname`` inherits."""
    if _is_filter(_class_from(module, objname)):
        return []
    return [row[1:] for row in _rows(module, objname, names) if _is_filter(row[0])]


def setup(app: Sphinx) -> dict[str, Any]:  # numpydoc ignore=RT01
    """Record the source directory the documented-class registry is built from."""
    global _srcdir  # noqa: PLW0603
    _srcdir = Path(app.srcdir)
    return {'parallel_read_safe': True, 'parallel_write_safe': True}
