"""Generate downloadable Python source files from docstring "Examples" sections.

This Sphinx extension looks, on every page, for numpydoc-style "Examples"
headings (rendered as ``.. rubric:: Examples`` for docstrings, or as a
regular section title for hand-written ``.. rst`` pages that happen to use
the same heading). Everything *outside* an Examples section is ignored
completely: pages/docstrings without one are left untouched, no file is
written and no link is added.

For each Examples section found, only the nodes belonging to that section
are converted into a small, self-contained, runnable Python script:

- doctest blocks (``>>> ...`` / ``... ...``) keep their code, with the
  prompts stripped, as real Python source
- ``.. code-block:: python`` (or ``py``) blocks are kept as-is
- everything else (prose, captions, non-python code, doctest output) is
  turned into a ``#`` comment
- figures/images generated by directives such as ``pyvista-plot`` are
  ignored

If the resulting script contains at least one real executable statement, a
download link for it is inserted immediately below the Examples section
(i.e. at the very end of that section, not at the end of the page).
"""

from __future__ import annotations

import ast
import hashlib
from pathlib import Path
from typing import TYPE_CHECKING

from docutils import nodes
from sphinx import addnodes
from sphinx.util import logging

if TYPE_CHECKING:
    from sphinx.application import Sphinx

logger = logging.getLogger(__name__)

# Node types that mark a heading (the start of some other section) and
# therefore bound the end of whatever Examples section precedes them.
# ``addnodes.desc`` and ``addnodes.index`` are included because numpydoc
# renders a class's nested members (e.g. ``:members:``) as flat siblings
# directly inside the *same* ``desc_content`` as the class's own Examples
# section -- without stopping there, a class's Examples section would
# swallow all of its methods too.
_BOUNDARY_TYPES = (
    nodes.rubric,
    nodes.title,
    nodes.section,
    addnodes.desc,
    addnodes.index,
)

# Node types with no textual content worth keeping (images/figures produced
# by plot directives, and docutils/numpydoc's own bookkeeping comments).
_IGNORED_TYPES = (nodes.image, nodes.figure, nodes.comment)

_CONTAINER_TYPES = (
    nodes.bullet_list,
    nodes.enumerated_list,
    nodes.definition_list,
    nodes.definition_list_item,
    nodes.list_item,
    nodes.definition,
    nodes.term,
    nodes.classifier,
    nodes.block_quote,
    nodes.note,
    nodes.warning,
    nodes.admonition,
    nodes.container,
    nodes.compound,
)

_PYTHON_LANGUAGES = ('python', 'py', 'python3')


def _is_examples_heading(node: nodes.Node) -> bool:
    """Check whether ``node`` is a heading (rubric or title) named "Examples"."""
    return (
        isinstance(node, (nodes.rubric, nodes.title))
        and node.astext().strip().lower() == 'examples'
    )


def _add_comment(lines: list[str], text: str) -> None:
    """Append ``text`` to ``lines`` as one or more Python comment lines."""
    for line in text.splitlines():
        line_ = line.rstrip()
        lines.append(f'# {line_}' if line_ else '#')


def _convert_doctest_block(node: nodes.doctest_block, lines: list[str]) -> bool:
    """Convert a doctest block, stripping ``>>> ``/``... `` prompts.

    Non-prompted lines (expected doctest output) become comments.
    """
    has_code = False
    for line in node.astext().splitlines():
        if line.startswith('>>> ') or line == '>>>':
            lines.append(line[4:])
            has_code = True
        elif line.startswith('... ') or line == '...':
            lines.append(line[4:])
        elif line.strip():
            _add_comment(lines, line)
        else:
            lines.append('')
    return has_code


def _convert_literal_block(node: nodes.literal_block, lines: list[str]) -> bool:
    """Convert a ``.. code-block::``. Python blocks stay code, others become comments."""
    language = node.get('language', '')
    if language in _PYTHON_LANGUAGES:
        lines.extend(node.astext().splitlines())
        return True
    _add_comment(lines, node.astext())
    return False


def _convert_node(node: nodes.Node, lines: list[str]) -> bool:
    """Append ``node``'s contribution to ``lines``.

    Returns whether any real executable code was added.
    """
    if isinstance(node, _IGNORED_TYPES):
        return False
    if isinstance(node, nodes.doctest_block):
        return _convert_doctest_block(node, lines)
    if isinstance(node, nodes.literal_block):
        return _convert_literal_block(node, lines)
    if isinstance(node, _CONTAINER_TYPES):
        has_code = False
        for child in node.children:
            has_code = _convert_node(child, lines) or has_code
        return has_code

    # Plain text-bearing nodes (paragraphs, admonition titles, etc.)
    text = node.astext().strip()
    if text:
        _add_comment(lines, text)
    return False


def _has_real_code(source: str) -> bool:
    """Check whether ``source`` contains at least one executable statement."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return False

    return any(
        not isinstance(stmt, ast.Expr) or not isinstance(stmt.value, ast.Constant)
        for stmt in tree.body
    )


def _collect_examples_span(heading: nodes.Node) -> tuple[nodes.Element, int, int]:
    """Return ``(parent, start_index, end_index)`` for the Examples section content.

    ``parent.children[start_index:end_index]`` are the nodes belonging to the
    Examples section that starts at ``heading``. ``end_index`` is also where a
    download link for this section should be inserted.
    """
    parent = heading.parent
    start = parent.index(heading) + 1
    end = start
    for i in range(start, len(parent.children)):
        if isinstance(parent.children[i], _BOUNDARY_TYPES):
            break
        end = i + 1
    return parent, start, end


def _qualified_name_for(heading: nodes.Node, docname: str, counter: int) -> str:
    """Best-effort identifier used to name the generated file."""
    node: nodes.Node | None = heading.parent
    while node is not None:
        if isinstance(node, addnodes.desc):
            signature = node.next_node(addnodes.desc_signature)
            if signature is not None and signature.get('ids'):
                return signature['ids'][0]
        node = node.parent
    base = Path(docname).name or docname
    return f'{base}-examples-{counter}'


def _write_source(app: Sphinx, name: str, source: str) -> str:
    """Write generated Python source directly into the builder's downloads dir.

    Returns the path of the written file, relative to the downloads
    directory (i.e. the value to use as a ``download_reference``'s
    ``filename`` attribute).

    Note: this writes straight to ``<outdir>/_downloads/...`` instead of
    registering through ``env.dlfiles``, because the HTML builder's
    ``copy_download_files`` task (which copies everything registered in
    ``env.dlfiles``) runs during ``copy_assets()`` -- *before* any
    ``doctree-resolved`` handler (this one included) gets a chance to run.
    Registering through ``env.dlfiles`` here would silently be too late.
    """
    digest = hashlib.sha256(source.encode()).hexdigest()[:16]
    safe_name = name.replace('.', '_') if name else 'example'
    rel_path = f'{digest}/{safe_name}.py'

    out_path = Path(app.outdir) / '_downloads' / digest / f'{safe_name}.py'
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(source, encoding='utf-8')
    return rel_path


def _make_download_node(rel_path: str) -> nodes.paragraph:
    """Build a working download link node for a file already in the downloads dir."""
    reference = addnodes.download_reference('', reftarget=rel_path)
    reference['filename'] = rel_path
    reference += nodes.Text('Download this example as a Python script')

    paragraph = nodes.paragraph()
    paragraph += reference
    return paragraph


def _process_doctree(app: Sphinx, doctree: nodes.document, docname: str) -> None:
    """Add a download link below every "Examples" section found on this page."""
    if not getattr(app.builder, 'download_support', False):
        # Only HTML-family builders (html, dirhtml, singlehtml, ...) know how
        # to serve a ``_downloads/`` directory. Skip everything else (latex,
        # text, man, epub, ...) rather than writing files nobody can reach.
        return

    headings = list(doctree.findall(_is_examples_heading))

    for counter, heading in enumerate(headings, start=1):
        parent, start, end = _collect_examples_span(heading)

        lines: list[str] = []
        has_code = False
        for node in parent.children[start:end]:
            has_code = _convert_node(node, lines) or has_code

        if not has_code:
            continue

        source = '\n'.join(lines).strip() + '\n'
        if not _has_real_code(source):
            continue

        name = _qualified_name_for(heading, docname, counter)
        rel_path = _write_source(app, name, source)
        download_node = _make_download_node(rel_path)

        parent.insert(end, download_node)


def setup(app: Sphinx) -> dict:  # numpydoc ignore=RT01
    """Register the extension."""
    app.connect('doctree-resolved', _process_doctree)

    return {
        'version': '0.1',
        'parallel_read_safe': True,
        'parallel_write_safe': True,
    }
