# ### Merge dependabot PRs ###
# This workflow follows the example from
# https://github.com/ridedott/merge-me-action and works by default only for PRs
# created by dependabot and will merge them when all checks pass

name: Merge me!

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Continuous Integration'
permissions:
  pull-requests: write
  contents: write
jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          # PAT from pyvista-ci-bot using public repo read/write
          GITHUB_TOKEN: ${{ secrets.PYVISTA_CI_BOT_DEPENDABOT }}