name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "documentation, docker, maintenance, ignore-for-release, enhancement, bug"
      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "community-reviewed"
      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 0
          labels: "do-not-merge"
